
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import DScopeCoreContractArtifactJson from '../../target/dscope_core-DScopeCore.json' with { type: 'json' };
export const DScopeCoreContractArtifact = loadContractArtifact(DScopeCoreContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract DScopeCore;
 */
export class DScopeCoreContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, DScopeCoreContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): DScopeCoreContract {
    return Contract.at(address, DScopeCoreContract.artifact, wallet) as DScopeCoreContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, sponsor: AztecAddressLike, treasury: AztecAddressLike, system_finalizer: AztecAddressLike, participation_gate: AztecAddressLike, survey_key: FieldLike, metadata_hash: FieldLike, predicate_policy_hash: FieldLike, start_time: (bigint | number), end_time: (bigint | number), reward_pool_amount: FieldLike, claim_deadline: FieldLike, reward_enabled: FieldLike, minimum_sample_target: FieldLike, analytics_min_total_sample: FieldLike, analytics_min_segment_sample: FieldLike, analytics_visibility_mode: FieldLike) {
    return new DeployMethod<DScopeCoreContract>(PublicKeys.default(), wallet, DScopeCoreContractArtifact, (instance, wallet) => DScopeCoreContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, sponsor: AztecAddressLike, treasury: AztecAddressLike, system_finalizer: AztecAddressLike, participation_gate: AztecAddressLike, survey_key: FieldLike, metadata_hash: FieldLike, predicate_policy_hash: FieldLike, start_time: (bigint | number), end_time: (bigint | number), reward_pool_amount: FieldLike, claim_deadline: FieldLike, reward_enabled: FieldLike, minimum_sample_target: FieldLike, analytics_min_total_sample: FieldLike, analytics_min_segment_sample: FieldLike, analytics_visibility_mode: FieldLike) {
    return new DeployMethod<DScopeCoreContract>(publicKeys, wallet, DScopeCoreContractArtifact, (instance, wallet) => DScopeCoreContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof DScopeCoreContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<DScopeCoreContract['methods'][M]>
  ) {
    return new DeployMethod<DScopeCoreContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      DScopeCoreContractArtifact,
      (instance, wallet) => DScopeCoreContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return DScopeCoreContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(DScopeCoreContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'sponsor' | 'treasury' | 'system_finalizer' | 'participation_gate' | 'survey_key' | 'metadata_hash' | 'predicate_policy_hash' | 'start_time' | 'end_time' | 'result_hash' | 'distribution_hash' | 'finalized_at' | 'reward_pool_amount' | 'claim_deadline' | 'reward_enabled' | 'minimum_sample_target' | 'final_participant_count' | 'analytics_min_total_sample' | 'analytics_min_segment_sample' | 'analytics_visibility_mode' | 'cancel_reason_code' | 'status'> {
      return {
        sponsor: {
      slot: new Fr(1n),
    },
treasury: {
      slot: new Fr(2n),
    },
system_finalizer: {
      slot: new Fr(3n),
    },
participation_gate: {
      slot: new Fr(4n),
    },
survey_key: {
      slot: new Fr(5n),
    },
metadata_hash: {
      slot: new Fr(6n),
    },
predicate_policy_hash: {
      slot: new Fr(7n),
    },
start_time: {
      slot: new Fr(8n),
    },
end_time: {
      slot: new Fr(9n),
    },
result_hash: {
      slot: new Fr(10n),
    },
distribution_hash: {
      slot: new Fr(11n),
    },
finalized_at: {
      slot: new Fr(12n),
    },
reward_pool_amount: {
      slot: new Fr(13n),
    },
claim_deadline: {
      slot: new Fr(14n),
    },
reward_enabled: {
      slot: new Fr(15n),
    },
minimum_sample_target: {
      slot: new Fr(16n),
    },
final_participant_count: {
      slot: new Fr(17n),
    },
analytics_min_total_sample: {
      slot: new Fr(18n),
    },
analytics_min_segment_sample: {
      slot: new Fr(19n),
    },
analytics_visibility_mode: {
      slot: new Fr(20n),
    },
cancel_reason_code: {
      slot: new Fr(21n),
    },
status: {
      slot: new Fr(22n),
    }
      } as ContractStorageLayout<'sponsor' | 'treasury' | 'system_finalizer' | 'participation_gate' | 'survey_key' | 'metadata_hash' | 'predicate_policy_hash' | 'start_time' | 'end_time' | 'result_hash' | 'distribution_hash' | 'finalized_at' | 'reward_pool_amount' | 'claim_deadline' | 'reward_enabled' | 'minimum_sample_target' | 'final_participant_count' | 'analytics_min_total_sample' | 'analytics_min_segment_sample' | 'analytics_visibility_mode' | 'cancel_reason_code' | 'status'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** cancel_before_start(cancel_reason_code: field, current_time: integer) */
    cancel_before_start: ((cancel_reason_code: FieldLike, current_time: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(sponsor: struct, treasury: struct, system_finalizer: struct, participation_gate: struct, survey_key: field, metadata_hash: field, predicate_policy_hash: field, start_time: integer, end_time: integer, reward_pool_amount: field, claim_deadline: field, reward_enabled: field, minimum_sample_target: field, analytics_min_total_sample: field, analytics_min_segment_sample: field, analytics_visibility_mode: field) */
    constructor: ((sponsor: AztecAddressLike, treasury: AztecAddressLike, system_finalizer: AztecAddressLike, participation_gate: AztecAddressLike, survey_key: FieldLike, metadata_hash: FieldLike, predicate_policy_hash: FieldLike, start_time: (bigint | number), end_time: (bigint | number), reward_pool_amount: FieldLike, claim_deadline: FieldLike, reward_enabled: FieldLike, minimum_sample_target: FieldLike, analytics_min_total_sample: FieldLike, analytics_min_segment_sample: FieldLike, analytics_visibility_mode: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** finalize_results(result_hash: field, distribution_hash: field, final_participant_count: field, finalized_at: integer, current_time: integer) */
    finalize_results: ((result_hash: FieldLike, distribution_hash: FieldLike, final_participant_count: FieldLike, finalized_at: (bigint | number), current_time: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_analytics_min_segment_sample() */
    get_analytics_min_segment_sample: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_analytics_min_total_sample() */
    get_analytics_min_total_sample: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_analytics_visibility_mode() */
    get_analytics_visibility_mode: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_cancel_reason_code() */
    get_cancel_reason_code: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_claim_deadline() */
    get_claim_deadline: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_distribution_hash() */
    get_distribution_hash: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_end_time() */
    get_end_time: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_final_participant_count() */
    get_final_participant_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_finalized_at() */
    get_finalized_at: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_metadata_hash() */
    get_metadata_hash: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_minimum_sample_target() */
    get_minimum_sample_target: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_participation_gate() */
    get_participation_gate: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_predicate_policy_hash() */
    get_predicate_policy_hash: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_result_hash() */
    get_result_hash: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_reward_enabled() */
    get_reward_enabled: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_reward_pool_amount() */
    get_reward_pool_amount: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_sponsor() */
    get_sponsor: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_start_time() */
    get_start_time: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_status() */
    get_status: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_survey_key() */
    get_survey_key: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_system_finalizer() */
    get_system_finalizer: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_treasury() */
    get_treasury: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
