
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import SurveyFactoryContractArtifactJson from '../../target/survey_factory-SurveyFactory.json' with { type: 'json' };
export const SurveyFactoryContractArtifact = loadContractArtifact(SurveyFactoryContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract SurveyFactory;
 */
export class SurveyFactoryContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, SurveyFactoryContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): SurveyFactoryContract {
    return Contract.at(address, SurveyFactoryContract.artifact, wallet) as SurveyFactoryContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, registry_operator: AztecAddressLike, system_finalizer: AztecAddressLike) {
    return new DeployMethod<SurveyFactoryContract>(PublicKeys.default(), wallet, SurveyFactoryContractArtifact, (instance, wallet) => SurveyFactoryContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, registry_operator: AztecAddressLike, system_finalizer: AztecAddressLike) {
    return new DeployMethod<SurveyFactoryContract>(publicKeys, wallet, SurveyFactoryContractArtifact, (instance, wallet) => SurveyFactoryContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof SurveyFactoryContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<SurveyFactoryContract['methods'][M]>
  ) {
    return new DeployMethod<SurveyFactoryContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      SurveyFactoryContractArtifact,
      (instance, wallet) => SurveyFactoryContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return SurveyFactoryContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(SurveyFactoryContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'registry_operator' | 'system_finalizer' | 'survey_count' | 'survey_address_by_id' | 'sponsor_by_id' | 'created_at_by_id' | 'survey_id_by_address' | 'survey_id_by_key' | 'survey_key_by_id' | 'survey_address_by_key' | 'participation_gate_by_key' | 'reward_vault_by_key' | 'predicate_policy_hash_by_key' | 'sponsor_by_key' | 'created_at_by_key' | 'metadata_hash_by_key' | 'start_time_by_key' | 'end_time_by_key' | 'system_finalizer_by_key'> {
      return {
        registry_operator: {
      slot: new Fr(1n),
    },
system_finalizer: {
      slot: new Fr(2n),
    },
survey_count: {
      slot: new Fr(3n),
    },
survey_address_by_id: {
      slot: new Fr(4n),
    },
sponsor_by_id: {
      slot: new Fr(5n),
    },
created_at_by_id: {
      slot: new Fr(6n),
    },
survey_id_by_address: {
      slot: new Fr(7n),
    },
survey_id_by_key: {
      slot: new Fr(8n),
    },
survey_key_by_id: {
      slot: new Fr(9n),
    },
survey_address_by_key: {
      slot: new Fr(10n),
    },
participation_gate_by_key: {
      slot: new Fr(11n),
    },
reward_vault_by_key: {
      slot: new Fr(12n),
    },
predicate_policy_hash_by_key: {
      slot: new Fr(13n),
    },
sponsor_by_key: {
      slot: new Fr(14n),
    },
created_at_by_key: {
      slot: new Fr(15n),
    },
metadata_hash_by_key: {
      slot: new Fr(16n),
    },
start_time_by_key: {
      slot: new Fr(17n),
    },
end_time_by_key: {
      slot: new Fr(18n),
    },
system_finalizer_by_key: {
      slot: new Fr(19n),
    }
      } as ContractStorageLayout<'registry_operator' | 'system_finalizer' | 'survey_count' | 'survey_address_by_id' | 'sponsor_by_id' | 'created_at_by_id' | 'survey_id_by_address' | 'survey_id_by_key' | 'survey_key_by_id' | 'survey_address_by_key' | 'participation_gate_by_key' | 'reward_vault_by_key' | 'predicate_policy_hash_by_key' | 'sponsor_by_key' | 'created_at_by_key' | 'metadata_hash_by_key' | 'start_time_by_key' | 'end_time_by_key' | 'system_finalizer_by_key'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(registry_operator: struct, system_finalizer: struct) */
    constructor: ((registry_operator: AztecAddressLike, system_finalizer: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_created_at_by_id(survey_id: field) */
    get_created_at_by_id: ((survey_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_created_at_by_key(survey_key: field) */
    get_created_at_by_key: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_end_time_by_key(survey_key: field) */
    get_end_time_by_key: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_latest_survey_id() */
    get_latest_survey_id: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_metadata_hash_by_key(survey_key: field) */
    get_metadata_hash_by_key: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_participation_gate_by_key(survey_key: field) */
    get_participation_gate_by_key: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_predicate_policy_hash_by_key(survey_key: field) */
    get_predicate_policy_hash_by_key: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_registry_operator() */
    get_registry_operator: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_reward_vault_by_key(survey_key: field) */
    get_reward_vault_by_key: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_sponsor_by_id(survey_id: field) */
    get_sponsor_by_id: ((survey_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_sponsor_by_key(survey_key: field) */
    get_sponsor_by_key: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_start_time_by_key(survey_key: field) */
    get_start_time_by_key: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_survey_address_by_id(survey_id: field) */
    get_survey_address_by_id: ((survey_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_survey_address_by_key(survey_key: field) */
    get_survey_address_by_key: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_survey_count() */
    get_survey_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_survey_id_by_address(survey_address: struct) */
    get_survey_id_by_address: ((survey_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_survey_id_by_key(survey_key: field) */
    get_survey_id_by_key: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_survey_key_by_id(survey_id: field) */
    get_survey_key_by_id: ((survey_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_system_finalizer() */
    get_system_finalizer: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_system_finalizer_by_key(survey_key: field) */
    get_system_finalizer_by_key: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_registered(survey_address: struct) */
    is_registered: ((survey_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_survey_key_registered(survey_key: field) */
    is_survey_key_registered: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_survey(survey_address: struct, sponsor: struct, created_at: integer) */
    register_survey: ((survey_address: AztecAddressLike, sponsor: AztecAddressLike, created_at: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_survey_with_config(survey_key: field, survey_address: struct, participation_gate: struct, reward_vault: struct, predicate_policy_hash: field, sponsor: struct, metadata_hash: field, start_time: integer, end_time: integer, system_finalizer: struct, created_at: integer) */
    register_survey_with_config: ((survey_key: FieldLike, survey_address: AztecAddressLike, participation_gate: AztecAddressLike, reward_vault: AztecAddressLike, predicate_policy_hash: FieldLike, sponsor: AztecAddressLike, metadata_hash: FieldLike, start_time: (bigint | number), end_time: (bigint | number), system_finalizer: AztecAddressLike, created_at: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_survey_with_key(survey_key: field, survey_address: struct, participation_gate: struct, reward_vault: struct, predicate_policy_hash: field, sponsor: struct, created_at: integer) */
    register_survey_with_key: ((survey_key: FieldLike, survey_address: AztecAddressLike, participation_gate: AztecAddressLike, reward_vault: AztecAddressLike, predicate_policy_hash: FieldLike, sponsor: AztecAddressLike, created_at: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_system_finalizer(new_system_finalizer: struct) */
    update_system_finalizer: ((new_system_finalizer: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
