
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import RewardVaultMVPContractArtifactJson from '../../target/reward_vault_mvp-RewardVaultMVP.json' with { type: 'json' };
export const RewardVaultMVPContractArtifact = loadContractArtifact(RewardVaultMVPContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract RewardVaultMVP;
 */
export class RewardVaultMVPContract extends ContractBase {

  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, RewardVaultMVPContractArtifact, wallet);
  }



  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): RewardVaultMVPContract {
    return Contract.at(address, RewardVaultMVPContract.artifact, wallet) as RewardVaultMVPContract;
  }


  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, operator: AztecAddressLike) {
    return new DeployMethod<RewardVaultMVPContract>(PublicKeys.default(), wallet, RewardVaultMVPContractArtifact, (instance, wallet) => RewardVaultMVPContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, operator: AztecAddressLike) {
    return new DeployMethod<RewardVaultMVPContract>(publicKeys, wallet, RewardVaultMVPContractArtifact, (instance, wallet) => RewardVaultMVPContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof RewardVaultMVPContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<RewardVaultMVPContract['methods'][M]>
  ) {
    return new DeployMethod<RewardVaultMVPContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      RewardVaultMVPContractArtifact,
      (instance, wallet) => RewardVaultMVPContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }



  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return RewardVaultMVPContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(RewardVaultMVPContractArtifactJson as NoirCompiledContract);
  }


  public static get storage(): ContractStorageLayout<'operator' | 'reward_enabled_by_key' | 'reward_pool_amount_by_key' | 'claim_deadline_by_key' | 'final_participant_count_by_key' | 'reward_per_participant_by_key' | 'total_allocated_by_key' | 'dust_return_to_sponsor_by_key' | 'distribution_hash_by_key' | 'finalized_at_by_key' | 'reward_status_by_key'> {
      return {
        operator: {
      slot: new Fr(1n),
    },
reward_enabled_by_key: {
      slot: new Fr(2n),
    },
reward_pool_amount_by_key: {
      slot: new Fr(3n),
    },
claim_deadline_by_key: {
      slot: new Fr(4n),
    },
final_participant_count_by_key: {
      slot: new Fr(5n),
    },
reward_per_participant_by_key: {
      slot: new Fr(6n),
    },
total_allocated_by_key: {
      slot: new Fr(7n),
    },
dust_return_to_sponsor_by_key: {
      slot: new Fr(8n),
    },
distribution_hash_by_key: {
      slot: new Fr(9n),
    },
finalized_at_by_key: {
      slot: new Fr(10n),
    },
reward_status_by_key: {
      slot: new Fr(11n),
    }
      } as ContractStorageLayout<'operator' | 'reward_enabled_by_key' | 'reward_pool_amount_by_key' | 'claim_deadline_by_key' | 'final_participant_count_by_key' | 'reward_per_participant_by_key' | 'total_allocated_by_key' | 'dust_return_to_sponsor_by_key' | 'distribution_hash_by_key' | 'finalized_at_by_key' | 'reward_status_by_key'>;
    }


  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {

    /** close_claims(survey_key: field, current_time: integer) */
    close_claims: ((survey_key: FieldLike, current_time: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(operator: struct) */
    constructor: ((operator: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** finalize_reward_distribution(survey_key: field, final_participant_count: integer, distribution_hash: field, finalized_at: integer) */
    finalize_reward_distribution: ((survey_key: FieldLike, final_participant_count: (bigint | number), distribution_hash: FieldLike, finalized_at: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_claim_deadline(survey_key: field) */
    get_claim_deadline: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_distribution_hash(survey_key: field) */
    get_distribution_hash: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_dust_return_to_sponsor(survey_key: field) */
    get_dust_return_to_sponsor: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_final_participant_count(survey_key: field) */
    get_final_participant_count: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_finalized_at(survey_key: field) */
    get_finalized_at: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_operator() */
    get_operator: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_reward_enabled(survey_key: field) */
    get_reward_enabled: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_reward_per_participant(survey_key: field) */
    get_reward_per_participant: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_reward_pool_amount(survey_key: field) */
    get_reward_pool_amount: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_reward_status(survey_key: field) */
    get_reward_status: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_allocated(survey_key: field) */
    get_total_allocated: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_reward_config(survey_key: field, reward_enabled: integer, reward_pool_amount: integer, claim_deadline: integer) */
    register_reward_config: ((survey_key: FieldLike, reward_enabled: (bigint | number), reward_pool_amount: (bigint | number), claim_deadline: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };


}
