
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import ParticipationGateV2ContractArtifactJson from '../../target/participation_gate_v2-ParticipationGateV2.json' with { type: 'json' };
export const ParticipationGateV2ContractArtifact = loadContractArtifact(ParticipationGateV2ContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract ParticipationGateV2;
 */
export class ParticipationGateV2Contract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, ParticipationGateV2ContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): ParticipationGateV2Contract {
    return Contract.at(address, ParticipationGateV2Contract.artifact, wallet) as ParticipationGateV2Contract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, issuer: AztecAddressLike, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<ParticipationGateV2Contract>(
      wallet,
      {
        artifact: ParticipationGateV2ContractArtifact,
        postDeployCtor: (instance, wallet) => ParticipationGateV2Contract.at(instance.address, wallet),
        args: [issuer],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof ParticipationGateV2Contract['methods']>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions },
    ...args: Parameters<ParticipationGateV2Contract['methods'][M]>
  ) {
    return DeployMethod.create<ParticipationGateV2Contract>(
      opts.wallet,
      {
        artifact: ParticipationGateV2ContractArtifact,
        postDeployCtor: (instance, wallet) => ParticipationGateV2Contract.at(instance.address, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? 'constructor',
      },
      opts.instantiation,
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return ParticipationGateV2ContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(ParticipationGateV2ContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'issuer' | 'credentials' | 'participation_receipts' | 'participation_consumptions' | 'survey_participation_count' | 'survey_policy_hash_by_key' | 'survey_age_mode_by_key' | 'survey_age_mask_by_key' | 'survey_country_mode_by_key' | 'survey_country_bitmap_by_key' | 'survey_start_time_by_key' | 'survey_end_time_by_key' | 'survey_policy_configured_by_key'> {
      return {
        issuer: {
      slot: new Fr(1n),
    },
credentials: {
      slot: new Fr(3n),
    },
participation_receipts: {
      slot: new Fr(4n),
    },
participation_consumptions: {
      slot: new Fr(5n),
    },
survey_participation_count: {
      slot: new Fr(6n),
    },
survey_policy_hash_by_key: {
      slot: new Fr(7n),
    },
survey_age_mode_by_key: {
      slot: new Fr(8n),
    },
survey_age_mask_by_key: {
      slot: new Fr(9n),
    },
survey_country_mode_by_key: {
      slot: new Fr(10n),
    },
survey_country_bitmap_by_key: {
      slot: new Fr(11n),
    },
survey_start_time_by_key: {
      slot: new Fr(12n),
    },
survey_end_time_by_key: {
      slot: new Fr(13n),
    },
survey_policy_configured_by_key: {
      slot: new Fr(14n),
    }
      } as ContractStorageLayout<'issuer' | 'credentials' | 'participation_receipts' | 'participation_consumptions' | 'survey_participation_count' | 'survey_policy_hash_by_key' | 'survey_age_mode_by_key' | 'survey_age_mask_by_key' | 'survey_country_mode_by_key' | 'survey_country_bitmap_by_key' | 'survey_start_time_by_key' | 'survey_end_time_by_key' | 'survey_policy_configured_by_key'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** activate_policy_config(survey_key: field) */
    activate_policy_config: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** assert_survey_participation_count(survey_key: field, expected_count: field) */
    assert_survey_participation_count: ((survey_key: FieldLike, expected_count: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(issuer: struct) */
    constructor: ((issuer: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** consumption_count_of(owner: struct) */
    consumption_count_of: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_age_mask(survey_key: field) */
    get_age_mask: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_age_mode(survey_key: field) */
    get_age_mode: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_country_bitmap_chunk(survey_key: field, chunk_index: integer) */
    get_country_bitmap_chunk: ((survey_key: FieldLike, chunk_index: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_country_mode(survey_key: field) */
    get_country_mode: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_issuer() */
    get_issuer: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_policy_configured(survey_key: field) */
    get_policy_configured: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_survey_end_time(survey_key: field) */
    get_survey_end_time: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_survey_participation_count(survey_key: field) */
    get_survey_participation_count: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_survey_policy_hash(survey_key: field) */
    get_survey_policy_hash: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_survey_start_time(survey_key: field) */
    get_survey_start_time: ((survey_key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** notes_of(owner: struct) */
    notes_of: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** participate(survey_key: field, expected_policy_hash: field, current_time: integer) */
    participate: ((survey_key: FieldLike, expected_policy_hash: FieldLike, current_time: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** receipt_count_of(owner: struct) */
    receipt_count_of: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_age_mask(survey_key: field, age_mask: integer) */
    register_age_mask: ((survey_key: FieldLike, age_mask: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_age_mode(survey_key: field, age_mode: integer) */
    register_age_mode: ((survey_key: FieldLike, age_mode: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_country_bitmap(survey_key: field, country_bitmap: array) */
    register_country_bitmap: ((survey_key: FieldLike, country_bitmap: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_country_mode(survey_key: field, country_mode: integer) */
    register_country_mode: ((survey_key: FieldLike, country_mode: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_policy_hash(survey_key: field, policy_hash: field) */
    register_policy_hash: ((survey_key: FieldLike, policy_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_survey_policy(survey_key: field, policy_hash: field, age_mode: integer, age_mask: integer, country_mode: integer, country_bitmap: array) */
    register_survey_policy: ((survey_key: FieldLike, policy_hash: FieldLike, age_mode: (bigint | number), age_mask: (bigint | number), country_mode: (bigint | number), country_bitmap: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_survey_window(survey_key: field, start_time: integer, end_time: integer) */
    register_survey_window: ((survey_key: FieldLike, start_time: (bigint | number), end_time: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** store_credential(to: struct, age_bucket: integer, country_bucket: integer, world_region: integer, valid_until: integer, source_tag: field, credential_version: field) */
    store_credential: ((to: AztecAddressLike, age_bucket: (bigint | number), country_bucket: (bigint | number), world_region: (bigint | number), valid_until: (bigint | number), source_tag: FieldLike, credential_version: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
